### ISSUE TITLE
Collation of redcap_project_stats table doesn't match REDCap conventions

### ISSUE THREAD

**Issue by pbchase** [ctsit/report_production_candidates#12]
The existing collation of the [redcap_project_stats table](https://github.com/ctsit/report_production_candidates/blob/73891f4c3e55a9d77dc9c7d24390c8d46363217a/ExternalModule.php#L48) is very inconvenient for joining it with other REDCap tables. I ran into this problem trying to join on username. The collation should be utf8_unicode_ci to match REDCap conventions.  e.g., the new table should be created as 

```
CREATE TABLE  redcap_project_stats (
    project_id int(10) PRIMARY KEY,
    saved_attribute_count int(10) UNSIGNED,
    last_user varchar(255)) collate utf8_unicode_ci
```

Any alter table statement on the existing table would need to convert the data in the table as well.  e.g.,

```
-- Fix collation in redcap_project_stats
alter table redcap_project_stats
CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
```

**Comment by tbembersimeao** [comment]
Fixed at https://github.com/ctsit/report_production_candidates/pull/13.
