### ISSUE TITLE
Use proper external module link and make it configurable

### ISSUE THREAD

**Issue by pbchase** [ctsit/report_production_candidates#22]
At 

https://github.com/ctsit/report_production_candidates/blob/bedca59502252c382c30e3bdc129b94110f03c7e/report.php#L78

Use proper external module link to Go Prod as documented under `getUrl` at https://github.com/vanderbilt/redcap-external-modules/blob/testing/docs/framework/v3.md

Add a module configuration in RPC to choose to use GoProd or not in RPC.

**Comment by pbchase** [comment]
@ChemiKyle, please ignore the "proper URL" thread. I was mistaken.  Sorry about the fool's errand.

All that said, please to continue to "Add a module configuration in RPC to choose to use GoProd or not in RPC."

**Comment by ChemiKyle** [comment]
Addressed by PR #24
