### ISSUE TITLE
Report columns would benefit from rescaling

### ISSUE THREAD

**Issue by pbchase** [ctsit/report_production_candidates#5]
The _Project Name_ and _Most Recent Activity_ columns in the report would be easier to read if they had a higher proportion of the available column width. To get a sense of this rename a project in the report to title of 60 characters. That length is not unusual. The average length of project titles in the UF CTSI REDCap system is 38. The standard deviation of those lengths is 32.

**Comment by rajputd** [comment]
closed by commit 3ef8a9584eb6489b24685ace4df2476754258b35
